version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor:
      name: node/default
      tag: '14.17.6'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: yarn test:ci
