import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tal Ohana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nostrum quam
        quas cupiditate, repellendus eligendi consectetur! Explicabo ut sequi
        officia. Provident aspernatur ut libero veniam illum, facilis dolore
        quia eius!
      </p>
    </div>
  );
};

export default Home;
